export const TOTAL_HEIGHT = 100;
export const TITLE_CONTAINER_HEIGHT = 18;
export const CHEVRON_HEIGHT = 12;
export const CHEVRON_BOTTOM_SPACE_HEIGHT = 7;
export const CHEVRON_CONTAINER_HEIGHT = CHEVRON_HEIGHT + CHEVRON_BOTTOM_SPACE_HEIGHT;